### ISSUE TITLE
Incorrect progress bar outline / alerts / active chip / badges states on Style Guide web

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#394]
Progress bar:

- [ ] Light and dark Mode Progress bar:  outline is Gray (`#6a6e79`) 6 both in Figma and XD, but indicates a non-palette color on style guide "border: 1px solid `#8c8b96`"

Alerts:

- [ ] Dark mode dark Alert outline should be changed from Gray 10 to Gray 8 `#464B52`
- [ ] The frame color of the secondary Alert is inconsistent (Gray 8 in both kits vs. Gray 6 on site). should be Gray 8 `#464B52`

Chips:

- [ ] Dark mode active Chip/solid should be Trimble Dark Mode Blue `#019AEB`, it is currently Trimble blue on Style Guide. Both Figma and XD is `#019AEB`

Badges:

- [ ] Light mode badges - warning badges have incorrect yellow on Style Guide. Currently on Yellow Dark. Both Figma and XD have correct Trimble Yellow `#FBAD26` with Trimble Gray label `#252A2E`
- [x] Dark mode - Dark badge label to be renamed to High Contrast

**Comment by soniakaukonen** [comment]
![image](https://user-images.githubusercontent.com/101354258/214639332-779fd21c-cd13-450b-989e-2faec509f65f.png)

**Comment by soniakaukonen** [comment]
![image](https://user-images.githubusercontent.com/101354258/214639451-1e1a2925-2d28-4dd5-a4ba-ca350a63dadd.png)

**Comment by soniakaukonen** [comment]
![Image](https://user-images.githubusercontent.com/101354258/214648397-9278f4fd-2c9c-4195-b19a-4c090eeb2dfc.png)

**Comment by msankaran0712** [comment]
hey @soniakaukonen is this issue present in other modus sites too? Like Modus Bootstrap, Modus React Bootstrap, and Modus Web components. If yes, we might have to create separate issue for each site.

**Comment by soniakaukonen** [comment]
As discussed, will issue shortly.

**Comment by soniakaukonen** [comment]
Issued.
